#! /bin/sh

ln --force --no-dereference --symbolic /usr/share/zoneinfo/"${TIMEZONE}" /etc/localtime
echo "${TIMEZONE}" > /etc/timezone

cd /opt/fhem
perl fhem.pl /etc/fhem.cfg
tail --follow /opt/fhem/log/fhem.log
